In [1]:
import numpy as np

## Data Types & Attributes

In [2]:
# NumPy's main datatype is ndArray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3.3], [4,5,6.6]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
# Create a DataFrame from a Numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.6

## 2.Creating Numpy arrays

In [13]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [14]:
ones = np.ones((2,3))

In [15]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
ones.dtype

dtype('float64')

In [17]:
zeros = np.zeros((2,3), dtype=int)

In [18]:
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [20]:
random_array = np.random.randint(0, 10, size=(3,5))

In [21]:
random_array

array([[1, 4, 4, 4, 8],
       [2, 7, 6, 5, 6],
       [5, 5, 2, 8, 3]])

In [22]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.64275699, 0.81966544, 0.04328789],
       [0.66423455, 0.17727492, 0.37219412],
       [0.62724334, 0.23703102, 0.85699967],
       [0.97967487, 0.99204788, 0.63272817],
       [0.32880072, 0.20999662, 0.64152053]])

In [23]:
random_array_2.shape

(5, 3)

In [24]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## 3. Viewing arrays and matrices

In [25]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Reshaping and transposing

In [26]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [27]:
a2.shape

(2, 3)

In [28]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.6]]])

In [29]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [105.6, 112.2, 118.8]]])

In [30]:
# Transpose = switches the axis
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.6]])

In [31]:
a2.T.shape

(3, 2)

In [32]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [33]:
a3.shape

(2, 3, 3)

In [34]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [35]:
a3.T.shape

(3, 3, 2)

# Dot Product

In [38]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [39]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [40]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [42]:
# Element-wise multiplication (Hadamard product)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [43]:
# Dot product
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [44]:
# Transpose mat1
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [45]:
mat1.T.shape

(3, 5)

In [46]:
mat3 = np.dot(mat1, mat2.T)

In [47]:
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [48]:
mat3.shape

(5, 5)

# Dot product example (nut butter sales)

In [49]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [51]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tue", "We", "Thurs", "Fri"], columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tue                3              3              7
We                 9             19             18
Thurs              4              6             12
Fri                1              6              7

In [52]:
# Create prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [53]:
prices.shape

(3,)

In [57]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3),
                            index=["Price"],
                             columns=["Almond Butter", "Peanut Butter", "Cashew Butter"]
                            )

In [58]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [59]:
total_sales = prices.dot(sales_amounts)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [60]:
# Shape aren't aligned, let's transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [63]:
# Create daily_sales
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [64]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tue   We  Thurs  Fri
Price  240  138  458    232  142

In [65]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tue                3              3              7
We                 9             19             18
Thurs              4              6             12
Fri                1              6              7

In [69]:
# Make it the right shape
weekly_sales["Total ($)"] = daily_sales.T

In [70]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon               12             15              0        240
Tue                3              3              7        138
We                 9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

### Comparison Operators

In [71]:
a1

array([1, 2, 3])

In [72]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

## 5. Sorting arrays

In [74]:
random_array

array([[1, 4, 4, 4, 8],
       [2, 7, 6, 5, 6],
       [5, 5, 2, 8, 3]])

In [75]:
np.sort(random_array)

array([[1, 4, 4, 4, 8],
       [2, 5, 6, 6, 7],
       [2, 3, 5, 5, 8]])

In [76]:
np.argsort(random_array)

array([[0, 1, 2, 3, 4],
       [0, 3, 2, 4, 1],
       [2, 4, 0, 1, 3]], dtype=int64)

## 6.Practical Example - NumPy in Action!!!!

In [77]:
<img src="images/panda.png" />

SyntaxError: invalid syntax (3003345584.py, line 1)